### ISSUE TITLE
提供一种兼容易用的方式跳过diff逻辑

### ISSUE THREAD

**Issue by army8735** [migijs/migi#10]
刚做完测试，知乎上出现类似提问，巧了。

一般随机数据的情况下，近似可以认为DOM变更在50%左右，倘若基数又大，那么直接innerHTML进行一次性重绘的时间记作t1，vd比对的时间记作t2，vd更新真实DOM的时间记作t3。

显然2者对比是t1和t2+t3的对比，在这种情况下由于t2的时间消耗导致t1反过来可能比t2+t3的时间要少。
因为t3=t1/2，而t2可能会>t3。

50%的变更率实际上是一个非常大的变更，在现实环境中非常难以见到，所以还没引起足够的重视和优化。

当更多问题暴露出来的时候，需求就会有了，那么此时应该增加一种设计接口：即在知道明显某个区域是大变化，应该省略diff直接进行重绘的时候，提供兼容易用的API显示声明这里别再diff，直接toString()渲染即可。

**Comment by hax** [comment]
我感觉这个事情如果能自动判定以自动为宜。人工标识这种为特例进行的性能优化对avg用户常常成为鸡肋。

**Comment by army8735** [comment]
这个想到了，因为自动判断实际是评估diff的多少。

追求准确的话真实计算diff，但其实不可能，白白浪费性能，只能从diff数量占总数量比>厥值来计算。这个智能评估本身会造成多少浪费还得想想。

**Comment by ziluo** [comment]
跑测试用例确实是发现React会比innerHTML慢，而慢的地方就在Dom Diff上，但如果能够实现数据和DOM之间双向绑定的话，是不是可以跳过Dom Diff，直接去更新DOM，感觉这样的性能会更好吧

感觉Virtual Dom的存在更多的是为跨语言开发而设计，单就这样的场景，反而会拉低性能

**Comment by army8735** [comment]
不涉及DOM变更的话是不做DomDiff的，数据变更（text或props）只进行DataDiff。

**Comment by army8735** [comment]
http://www.zhihu.com/question/31887150

**Comment by army8735** [comment]
#12
