### ISSUE TITLE
扩展jsx语法，onClick支持选择器

### ISSUE THREAD

**Issue by army8735** [migijs/migi#16]
``` jsx
<div onClick=['a', handler]><a>123</a></div>
```

事件代理，即可保持shadow作用域又能方便代理。

**Comment by hax** [comment]
语法略丑。可以这样不：

``` html
<div on-click(a)=handler><a>...</a></div>
```

或者这样的冗长版：

``` html
<div on-click=handler target-match="a.test"><a class=test>...</a></div>
```

**Comment by army8735** [comment]
-到没看到jsx里有这个规范，()里字符串？

``` jsx
<div onClick('a')={this.handler}><a>...</a></div>
```

js变量得{}

**Comment by ziluo** [comment]
这样做不太好吧，个人感觉在`handler`里面去做代理逻辑比较好。

另外，按照你的这种实现，如果我想在`div`上增加代理`span`标签的`click`事件的话该怎么实现呢？

**Comment by army8735** [comment]
handler里就是自己实现了。

onClick('a,span')={}，你不会连jq/zepto的on都忘了吧……

**Comment by ziluo** [comment]
不，我的意思的是a标签和span标签的回调不一样的情况，难道是写两个onClick？

**Comment by army8735** [comment]
对啊

**Comment by hax** [comment]
这是我自己拍脑袋想的。如果你要保持和jsx完全一致，就别考虑我的YY啦。

但如果选择允许自行扩展，则可以考虑一些其他的可能性。
话说 onclick 写两个这个事情确实是和html不一致的。所以从一致性和简单性上来说，xml events的方式更好一点：

``` html
<div><a>...</a><span>...</span></div>
<listener event='click' observer='div' target='a' handler=handlerForA />
<listener event='click' observer='div' target='span' handler=handlerForSpan />
```

（注意原始的xml events里指定用的都是id，我这里改为用selector了）

当然，这样就冗长，且绝大部分情况其实都只绑一个事件处理。

**Comment by hax** [comment]
另一方面，我建议的`on-event(target)=handler`的语法倒是可以满足更多区分的case。如：

``` html
<div on-click(a.link)=handler1 on-click(span)=handler2>...
```

语法上是两个不同的属性。

另外可以考虑支持捕捉：

``` html
<div capture-input(textarea)=handler>...
```

**Comment by army8735** [comment]
我在想hash也是个不错的选择：

``` jsx
<div onClick={{
  'a': handler1,
  'span': hander2
}}>
```

**Comment by hax** [comment]
弱弱问下，为啥需要双花括号？是因为单花括号直接是内插变量？

另外，hash看上去好像是ok的，但是总隐隐感觉有点不好，不知道为什么……

**Comment by army8735** [comment]
打得时候就知道会问哈哈。

jsx规范{}标明js语言开始，不是Obj的start，因此里面的Obj的花括号才是开始。但我想其实可以省略，只是感觉又和所谓的标准搞不同了。

这样写我能想到坑的就是默认的没有代理的需要定义个诸如default的特殊键名对应。

**Comment by hax** [comment]
因为es6有对象的缩写法，导致 `{x}` 产生歧义——等于一个对象`{x: x}`或者等于`x`的值，所以不能省略啊。

倒是不需要`default`，你直接支持 `onClick={handler}` 和 `onClick={{a: handlerForA, span: handlerForSpan}}` 两种（函数和对象）就好，不过这大概就是我觉得不爽的地方——编译时无法确定是哪一种（除非你要求后一种必须是对象literal）。

**Comment by army8735** [comment]
肯定强类型！

`onClick={handler}`和`onClick={{a: handlerForA, span: handlerForSpan}}`同时出现就会出现上面说的和html不一致了
