### ISSUE TITLE
设计想法

### ISSUE THREAD

**Issue by army8735** [migijs/migi#4]
http://army8735.me/migijs/migi/demo/

目前demo可在以上访问。
- 整体分为3个部分：migi是基础库/框架，lefty是预编译器，jaw是转化css进入内联style的组件预编译器。
- 基于JSX语法，因此看上去和React非常像，本来就是借鉴了不少。其实我感觉有了JSX后，其它模板语言将面临极大的竞争。
- 基于get/set的双向mvvm绑定，这和React完全不一样。但是我对get/set也是新手，目前原理就是set方法末尾编译追加事件侦听。希望有经验的人能给予帮助。比如对引用操作时set根本不起作用，除非自己赋值自己一遍。虽然可以在预编译器自动增加赋值，但其覆盖是一方面问题，性能也是另外一方面问题。
- 偏OOP风格，可以看到NonVisualComponent和CacheComponent都继承自Component。
- Component是个自定义组件基类，而真正的DOM则在其VirtualDom属性上，2者分开。
- css预编译内联需要强大的分析器，目前parser储备充足，正在慢慢实现。静态的JSX写入还算简单；动态的（变量中未知的JSX、:first-child）需要运行时插入；一些伪类（:hover,:active）需要migi提供接口，侦听onmouseover之类完成；::visited等则完全无法实现，好在极少用到；对webcomponent设置内部组件的伪类，也需动态。
- 不排他。体积很小，风格也是立足于功能点，没涉及到的不做方便扩展。
- webcomponent特性，囊括html、js、css，组件为单一静态资源，shadow化。

**Comment by xufei** [comment]
不一定都是在set末尾加，很多时候，在get上加东西，会是更清晰的。

**Comment by army8735** [comment]
比如？

现在是set时触发事件，然后预编译时期记录下来的对应get去更新检查，发现变更则进行数据更新。get上加东西怎么弄？

**Comment by xufei** [comment]
看一下aurelia的处理方式：

``` JavaScript
export class Person {
  firstName = 'John';
  lastName = 'Doe';

  @computedFrom('firstName', 'lastName')
  get fullName(){
    return `${this.firstName} ${this.lastName}`;
  }
}
```

看这里的fullName，一般来说，大家不想在get上加的原因是，不知道什么时候应当调用，所以angular是不管你是否需要都重新算，但是有的框架是这样，由使用方去标记一下，对于有标记的，每次都算，这是个折中的选择，性能不是特别差，语义也会比较好。

类似，knockout的：

``` JavaScript
var ViewModel = function(first, last) {
    this.firstName = ko.observable(first);
    this.lastName = ko.observable(last);

    this.fullName = ko.pureComputed(function() {
        // Knockout tracks dependencies automatically. It knows that fullName depends on firstName and lastName, because these get called when evaluating fullName.
        return this.firstName() + " " + this.lastName();
    }, this);
};
```

**Comment by army8735** [comment]
没太明白这样的优点是什么？
注解标记是个很好的语法，显示声明，曾经想过这方面的内容。
这里标记get后……

**Comment by xufei** [comment]
你原先是每次set firstName和lastName的时候，都会要触发所有对firstName和lastName关联的变更，但其实并不需要立即这样，这里可以先记录，然后最后合并，等它用fullName的时候，再去动态算最新的

**Comment by army8735** [comment]
你的意思应该是：

``` js
person.firstName = 'a';
persion.lastName = 'b';
```

现在方式会触发2次计算并更新吧？

改成显示声明后，记录用fullName的地方，和关联firstName和lastName。
依旧发生上述操作后，每次变动做个记录缓存。
等2次赋值结束后，检查发现的变更，发现firstName和lastName改变了。
检查关联，发现需要更新fullName。
找到记录用fullName的地方，更新视图。

这里get和set应该都需要加东西。

**Comment by xufei** [comment]
是都要加，但意义不同。比如说有一个视图和一段模型，set的东西，一般是针对原始模型的，而get的东西是针对视图模型的。

对于上面这个简单的例子，虽然可以把firstName，lastName，fullName都放在model中，但我认为只应当放前两个，fullName应当是在更上一层，模型的数据还是要尽可能精简。

这样看的话，set和get的职责可以分得很清楚，凡是set，都转到model去，凡是get，都取给vm用，这样划分，在多次读写合并的时候应该会方便一些。

**Comment by army8735** [comment]
```
@computedFrom('firstName', 'lastName')
get fullName(){
    return `${this.firstName} ${this.lastName}`;
}
```

感觉似乎可以自动提取出来不用声明，但又会有特别复杂的情况误伤……

**Comment by xufei** [comment]
自动不了，getter里面只要一有函数调用就做不下去了……

**Comment by army8735** [comment]
顺着思路想下去，一种方式可以基本避免增加注解语法且解决声明来源这个问题：
由于存在初始化，所以在get中也增加埋点。

``` jsx
class Person{
  constructor() {
    this._first = '';
    this._last = '';
  }
  get first() {//埋点get frist
    return this._first;
  }
  set first(v) {
    this._first = v;
  }
  get last() {//埋点get last
    return this._last;
  }
  set last(v) {
    this._last = v;
  }
  get name() {
    return this.first + this.last;
  }
  render() {
    return <div>{this.name}</div>;
  }
}
var person = new Person();
person.render();
person.first = 'xxx';
```

在初始化时：
- 取{this.name}前记录下我要取this.name
- 开始取，计算first+last，由于存在埋点，知道name依赖first和last
- 取结束，获得依赖关系

但能想到2个缺点：
- first和last可能没有get：但这个可以编译器自动添加
- get name中存在if逻辑可能导致某个变量没get到，从而没触发埋点：这个情况较少，可以用显示声明来弥补，另外预编译器尽可能多地分析覆盖到

是否有漏洞？

**Comment by army8735** [comment]
自动添加get也有隐患，需要分析set的是哪个变量。

``` es6
class Person{
  get name(first, last) {
    return this._first + this._last;
  }
}
```

感觉可以利用get那没用的形参来避免添加可能影响未来的注解语法。

**Comment by xufei** [comment]
在first和last的get里添加怎样的埋点才能知道name依赖first和last啊？

直接动模型层的get和set还会有别的问题，假如业务方要自己在model上定义get和set，就歇菜了……所以我还是觉得应该在vm层的get上做文章

**Comment by army8735** [comment]
``` jsx
class Person {
  constructor() {
    this._first = 'a';
    this._last = 'b';
  }
  get first() {
    return this._first;
  }
  get last() {
    return this._last ;
  }
  get name() {
    return this.first + this.last;
  }
  render() {
    return <a>{this.name}</a>;
  }
}
```

``` jsx
class Person {
  constructor() {
    this._first = 'a';
    this._last = 'b';
  }
  get first() {
    return this._first;
  }
  get last() {
    return this._last ;
  }
  get name() {
    return this.first + this.last;
  }
  render() {
    return migi.createElement("a",{},new migi.Obj("name",this,function(){return(this.name)}));
  }
}
```

模板那里将所有this.xxx的写成一个migi.Obj实例，记录了context和callback。
render()被调用时初始化渲染，遇到migi.Obj会调用下callback获取值，如是知道了name是取自first和last。
但是必须为first和last提供get方法，并且get name()里不能有if条件。
这条路也封死了。只能用显示声明。

**Comment by army8735** [comment]
@xufei 
http://army8735.me/migijs/migi/demo/explicit.html
这种显式声明分离对否？

**Comment by xufei** [comment]
我觉得这样是对的，但是这会对变更检测带来很大挑战。你现在是怎么做到在给first和last设置值的时候，触发name的get的？

**Comment by army8735** [comment]
编译期间做的，name的get变量上发现依赖first和last，于是给first和last的set添加通知name变更事件。

**Comment by xufei** [comment]
如果这个get，依赖的东西位于模型之外，就比较头疼了

**Comment by army8735** [comment]
或许可以考虑弄个专门的模型类，没有view的，外部的可以统一使用其进行管理数据，然后用bridge桥接起来。#8

**Comment by army8735** [comment]
@xufei 准备考虑弄个专门的model对象，先看看a家的设计方式

**Comment by hax** [comment]
计算值本身依赖的只能是模型里的其他属性。内部用到其他函数是没关系的——只要该函数是一个纯函数，就不会引入额外的依赖关系。

**Comment by xufei** [comment]
@hax 我同意你的观点，但有的框架不是这么想的，比如：http://blog.durandal.io/2015/05/13/aurelia-computed/

``` JavaScript
var _bar = 'baz';

export class Foo {

  // This property cannot be observed by aurelia-computed.
  // Dirty-checking will be required.
  // "_bar" can't be accessed from the binding scope.
  get bar() {
    return _bar;
  }
}
```

他连这个也愿意支持，用的是脏检测……

**Comment by army8735** [comment]
支持模型外的属性，设计考虑是啥……

**Comment by xufei** [comment]
我也不知道，觉得挺奇怪的。所以它就支持了各种变更检测方式……

**Comment by hax** [comment]
每个框架可以有各种想法嘛，设计目标不一样。

我个人不喜欢这种方式是因为我认为在实践中`_bar`要么是常量（因而无需observe），要么很容易重构为接受管理的属性。且我们这帮人开发（选择）框架的考虑除了提高效率之外，还有约束团队的开发方式，因此舍弃脏检测并没有什么不可以。
