### ISSUE TITLE
组件的数据联动

### ISSUE THREAD

**Issue by army8735** [migijs/migi#8]
目前的设计思路是提供2种：bind和bridge。

前者适用于完全相等的2个组件，同一个class出生，双向联动不是太常用。<br/>
示例使用了2个相同的选择省份下拉，一个变了另外一个跟着变。<br/>
http://army8735.me/migijs/migi/demo/bind.html

后者比较普遍，a桥接到b，当a的数据发生变化时，通过bridge提供的参数和中间件处理，把数据通信到b，b发生改变后更新。<br/>
示例使用了2级省市联动，省发生变更后市也跟着变。<br/>
http://army8735.me/migijs/migi/demo/bridge.html

**Comment by ziluo** [comment]
组件多了以后，bridge的方式也不是太好用，要人肉串起来，维护起来非常麻烦。

目前项目中的React Component之间的数据联动是采用mixin的方式来实现，如下，虽不完美，但也能满足大部分业务场景：

``` js

/** @jsx React.DOM */

/**
 * 公共模块引入
 */

var Events = require('arale-events');

Events.mixTo(window);

exports = module.exports ={

  getInitialState: function(){

    this.trigger = function(){
      window.trigger.apply(window, Array.prototype.slice.call(arguments, 0));
    };

    this.on = function(){
      window.on.apply(window,Array.prototype.slice.call(arguments, 0));
    };

    this.off = function(){
      window.off.apply(window,Array.prototype.slice.call(arguments, 0));
    };

    return {};
  }
};

```

引入该mixin之后，组件内就可以监听所有的全局事件变动，也可以触发全局事件，组件与组件之间的耦合也不会太严重，维护起来也相对方便些。

**Comment by army8735** [comment]
其实这种方式叫做事件总线，eventbus，migi上有个Event类，所有组件都是其实例。migi上还有个eventBus对象，就是充当你说的mixin功能的全局侦听。这几乎成为每个库的标配了。

**Comment by army8735** [comment]
在思考将eventBus之类的Event全部用bridge或bind串起来，毕竟每个vd的本质还是个Event。这样实际做了层统一的封装，vd.bridge(eventBus)，vd2.bridgeTo(eventBus)，bus成为中间代理通信人传递数据和数据变更。
